[package]
name = "lightweight-pdf-layout"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Layoutable trait, pagination and text wrapping for lightweight-pdf"

[dependencies]
hyphenation = { version = "0.8.4", features = ["embed_all"], optional = true }
lightweight-pdf-core = { path = "../lightweight-pdf-core", version = "0.3.0" }

[features]
hyphenation = ["dep:hyphenation"]
